/** Extract executable SQL from a fix_prompt (strips editor intro lines). */
export function extractSqlContent(fixPrompt: string): string {
  const lines = fixPrompt.split("\n");
  const sqlLines: string[] = [];
  let inSql = false;

  for (const line of lines) {
    const trimmed = line.trim();
    const looksLikeIntro =
      /^(run this|paste this|execute|sql editor|supabase|mysql|postgresql|in your)/i.test(
        trimmed
      ) && !/^(alter|create|drop|insert|update|delete|grant|revoke|enable)/i.test(trimmed);

    if (!inSql && looksLikeIntro) continue;
    if (!trimmed && !inSql) continue;

    inSql = true;
    sqlLines.push(line);
  }

  const sql = sqlLines.join("\n").trim();
  return sql || fixPrompt.trim();
}

export function slugifyMigrationName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 60) || "migration";
}

export function normalizeMigrationFilename(
  value: unknown,
  issueName: string
): string {
  if (typeof value === "string" && value.trim()) {
    return slugifyMigrationName(value.trim());
  }
  return slugifyMigrationName(issueName);
}

export function getMigrationTimestamp(date = new Date()): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}${m}${d}`;
}

export function formatMigrationDate(date = new Date()): string {
  return date.toLocaleDateString(undefined, {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

export function buildMigrationFilePath(
  migrationSlug: string,
  timestamp = getMigrationTimestamp()
): string {
  return `supabase/migrations/${timestamp}_${migrationSlug}.sql`;
}

export function buildMigrationFileContent(
  issueName: string,
  sqlContent: string,
  date = formatMigrationDate()
): string {
  return `-- Migration: ${issueName}
-- Generated by ShipProof on ${date}
-- Run this in Supabase SQL Editor if not already done

${sqlContent}`;
}

export function buildMigrationCreateFilePrompt(
  tool: string,
  filePath: string,
  issueName: string,
  sqlContent: string,
  date = formatMigrationDate()
): string {
  return `Create a new file at ${filePath} with this content:

-- Migration: ${issueName}
-- Generated by ShipProof ${date}

${sqlContent}

This documents the database change in version control.`;
}
